### PR TITLE
keep deploying binary of app

### PR DESCRIPTION
**Pull request by liudonghua123**
The continue work of https://github.com/tw93/Pake/pull/616.

### CODE REVIEW

**Comment by liudonghua123** [comment]
@tw93 Hi, could you merge this pr. I tested ok locally.

**Comment by tw93** [comment]
@liudonghua123 Thanks for the submission, here's a reference to the comment above, in addition to the hard work of merging directly into the dev branch, not into the master branch

**Comment by liudonghua123** [comment]
I see, I recreated the [pr](https://github.com/tw93/Pake/pull/706) which trying to merge into dev branch.

**Comment by tw93** [comment]
@liudonghua123 ok，Code modification and optimization also go together～～

**Comment by liudonghua123** [comment]
> @liudonghua123 ok，Code modification and optimization also go together～～

@tw93 hi, i have updated the pr. However, it should working even I have not rebased the pr branch since no conflicts around the modifications.

**Pull request closed without merging**
