### PR TITLE
keep deploying binary of app

### PR DESCRIPTION
**Pull request by liudonghua123**
PR for https://github.com/tw93/Pake/issues/615, tested ok locally.

image

### CODE REVIEW

**Comment by tw93** [comment]
Archive it first. I see some messages that have not been answered yet. If you see them, please try again and reopen them. Thank you!

**Comment by liudonghua123** [comment]
@tw93 How about now? 😄

**Comment by tw93** [comment]
@liudonghua123 🤔Need you to modify the code here
https://github.com/tw93/Pake/pull/616/files

**Comment by liudonghua123** [comment]
Hi, I rebased the pr, and it works still.

image

**Pull request closed without merging**
