### PR TITLE
Add docker image for linux

### PR DESCRIPTION
**Pull request by stone-w4tch3r**
Simplifies CLI usage on linux.

- Dockerfile
- workflow to build and publish image in github packages
- readme entry

P.S. unfortunately I started from `master` branch. Due to many diffs in `dev`, merging seems to be inappropriate now

### CODE REVIEW

**Comment by tw93** [comment]
Good Job！
Please help check if it can be merged. @stone-w4tch3r @Tlntin

**Comment by Tlntin** [comment]
Okay, I'll see

**Comment by Tlntin** [comment]
it seems work well in local.

**Comment by Tlntin** [comment]
but it not work well in github action😂

**Comment by tw93** [comment]
> but it not work well in github action😂

It still needs further optimization, and then we can take a look first. @stone-w4tch3r

**Comment by Tlntin** [comment]
i remove arm64 support, it work well.

**Comment by stone-w4tch3r** [comment]
> i removed arm64 support, it work well.

Its bad for arm64, I think ;-)

**Pull request merged**
